### ISSUE TITLE
Error with writetable()

### ISSUE THREAD

**Issue by mathtd** [FugroRoames/TypedTables.jl#4]
I tried to use writetable() to write a table in a file

```
using TypedTables
t = @Table(A=[1,2,3], B=[2.0,4.0,6.0])
writetable("test.txt",t)
```

I get the error
```
ERROR: UndefVarError: Types not defined
 in writetable at /Users/mathieu/.julia/v0.4/TypedTables/src/IO.jl:115
 in writetable at /Users/mathieu/.julia/v0.4/TypedTables/src/IO.jl:83
```

After loading the module Julia returns the warning
```
WARNING: New definition 
    promote_op(Type{#T<:Any}, Any) at /Users/mathieu/.julia/v0.4/NullableArrays/src/operators.jl:10
is ambiguous with: 
    promote_op(Any, Type{#R<:Number}) at /Users/mathieu/.julia/v0.4/NullableArrays/src/operators.jl:12.
To fix, define 
    promote_op(Type{#T<:Any}, Type{#R<:Number})
before the new definition.
```

**Comment by andyferris** [comment]
Sorry about that! It seems I forgot to add `Types` as a parameter in the `writetable` function. I'll fix it on Monday.

For now you could try converting to a DataFrame and using their support. Also checkout the *DataStreams..jl* - I think that TypedTables will be using that soon for all I/O also.

PS - don't worry about that warning,; it's a (minor) problem in a different package.

**Comment by andyferris** [comment]
This was fixed in 3e34ef26753a838ac13b44113af275b70600f0f8, no?

**Comment by mathtd** [comment]
I still get the same error using the latest version from Pkg.update()

**Comment by andyferris** [comment]
OK I'll have another look

**Comment by andyferris** [comment]
The master branch should work fine. The tests don't pass on v0.4 purely because of some [holes](https://github.com/JuliaLang/Compat.jl/issues/278) in *Compat.jl* but the actual writing should be working fine now. Let me know if there are any remaining issues, and I'll tag a release once I have a fix for the tests.

**Comment by mathtd** [comment]
Yes it works on master. Thanks!
